apiVersion: apps/v1
kind: Deployment
metadata:
  name: carsdeploy
  labels:
    app: carsdeployapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
        - name: carsimage
          image: acr25dec.azurecr.io/aksmlr:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: carsmlr-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: cars